### ISSUE TITLE
插件在jntspx无法生效,请求适配

### ISSUE THREAD

**Issue by Bin0Liu** [abcmouse/chinahrtAssistant#1]
**jntspx.chinahrt.com**
插件在上面的网址无法使用,是我使用的方法不对吗.请求指导

**Comment by Bin0Liu** [comment]
![image](https://user-images.githubusercontent.com/32361081/80689656-38f40b00-8b00-11ea-8116-85c3664dd339.png)

**Comment by Bin0Liu** [comment]
![image](https://user-images.githubusercontent.com/32361081/80691438-d6503e80-8b02-11ea-9da2-45c883efa90c.png)

**Comment by abcmouse** [comment]
please check the update.
